<a href="https://colab.research.google.com/github/DerekHickey6/derekhickey6.github.io/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import pandas as pd
import numpy as pd
import matplotlib.pyplot as plt

print(torch.__version__)

2.8.0+cu126


### Scalar/Vector/MATRIX/TENSOR

In [3]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [4]:
vector.shape

torch.Size([2])

In [5]:
MATRIX = torch.tensor([[7,6],
                       [8,9]])
MATRIX

tensor([[7, 6],
        [8, 9]])

In [6]:
MATRIX.ndim

2

In [7]:
MATRIX[1]

tensor([8, 9])

In [8]:
MATRIX.shape

torch.Size([2, 2])

In [9]:
MATRIX = torch.tensor([[7,6],
                       [8,9]])
MATRIX.shape

torch.Size([2, 2])

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [12]:
TENSOR.ndim

3

In [13]:
TENSOR.shape

torch.Size([1, 3, 3])

In [14]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random Tensors

In [15]:
# create random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.2643, 0.0055, 0.0473, 0.1483],
        [0.8759, 0.1713, 0.8977, 0.4739],
        [0.6295, 0.6084, 0.6022, 0.4697]])

In [16]:
random_tensor.ndim

2

In [17]:
# create a random tensor with similar shape as an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # color channels (R, G, B), height, width,
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Tensors of ones / zeros & Range

In [18]:
# Create a tensor of all zeros
zero = torch.zeros(3,4)
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [20]:
ones.dtype

torch.float32

In [21]:
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
# creating tensor-like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Data Types

In [23]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                                dtype=None,           # Data type of tensor
                                device=None,          # Device that tensor on
                                requires_grad=False)  # Tracks the gradients of a tensor while going through numerical calculations
float_32_tensor

tensor([3., 6., 9.])

In [24]:
float_32_tensor.dtype

torch.float32

In [25]:
float_16_tensor = float_32_tensor.type(torch.half)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [26]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors

1. get datatype from tensor `tensor.type`
2. get shape from tensor `tensor.shape`
3. get device from a tensor `tensor.device`


In [27]:
# Create a Tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.0487, 0.1333, 0.0750, 0.0999],
        [0.2447, 0.6156, 0.5454, 0.0787],
        [0.8515, 0.6741, 0.3919, 0.4555]])

In [28]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.0487, 0.1333, 0.0750, 0.0999],
        [0.2447, 0.6156, 0.5454, 0.0787],
        [0.8515, 0.6741, 0.3919, 0.4555]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


### Manipulating Tensor (operations)


In [29]:
# Create a tensor and add 100
tensor = torch.tensor([1,2,3])
tensor + 100

tensor([101, 102, 103])

In [30]:
# Tensor multiplied by 10
tensor * 10

tensor([10, 20, 30])

In [31]:
# subtract 10
tensor - 10

tensor([-9, -8, -7])

In [32]:
# Using PyTorch functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

### Matrix Multiplication

In [33]:
# Element Wise Multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")
tensor


tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


tensor([1, 2, 3])

In [34]:
# Matrix Multiplication
%%time
torch.matmul(torch.rand(50), torch.rand(50))

CPU times: user 881 µs, sys: 0 ns, total: 881 µs
Wall time: 13.3 ms


tensor(13.7212)

In [35]:
# Matrix multiplication by hand
%%time
value = 0
for i in range(len(tensor)):
  value += torch.rand(50)[i] * torch.rand(50)[i]
print(value)

tensor(0.8233)
CPU times: user 1.45 ms, sys: 64 µs, total: 1.52 ms
Wall time: 2.8 ms


In [36]:
# Other notation for matmul
tensor @ tensor

tensor(14)

In [37]:
# Shapes for matrix multiplications
tensor_A = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]])
tensor_B = torch.tensor([[7, 10],
                        [8, 11],
                        [9, 12]])
torch.mm(tensor_A, tensor_B.T)  # .T is transpose

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### Tensor Aggregation

In [38]:
# Finding the min, max, mean, etc
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [39]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [40]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [41]:
# Torch.mean requires float or complex dtype
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [42]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [43]:
# returnsindex of min or max
torch.argmin(x), torch.argmax(x)

(tensor(0), tensor(9))

In [44]:
x.argmin(), x.argmax()

(tensor(0), tensor(9))

### Reshaping, stacking, squeezing and unsqueezing

* Reshaping - reshapes and input tensor to a defined shape
* View - return a view of an input tensor of a certain shape but keep the same memory of original tensor
* Stacking - stacks tensors V-stack - vertical, H-stack - horizontal
* Squeeze - removes all `1` dimensions from a tensor
* unsqueeze - adds `1` dimension to out target tensor
* permute - return a view of the input with dimensions swapped

In [45]:
import torch

x = torch.arange(1, 10)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [46]:
# add extra dimension - must contain same amount of elements
x_reshape = x.reshape(1, 9)
x_reshape, x_reshape.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [47]:
# change the view - shares same memory as the same input
z = x.view(1, 9)
z, z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [48]:
# changing z, changes x
z[:, 0] = 5
z, x

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

In [49]:
# stack tensors on top - can also use .vstack & .hstack
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9]])

In [50]:
x_reshape.shape

torch.Size([1, 9])

In [51]:
x_reshape

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])

In [52]:
# removes all single (1) dimensions
x_reshape.squeeze()

tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
print(f"Previous tensor: {x_reshape}")
print(f"New tensor: {x_reshape.squeeze()}")

Previous tensor: tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])
New tensor: tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])


In [54]:
x_reshape.unsqueeze(dim=2).shape



torch.Size([1, 9, 1])

In [55]:
from os import XATTR_SIZE_MAX
# torch.permute - returns a view of the original tensor input with its dimensions permuted
x_original = torch.rand(224, 224, 3)

x_original.shape
x_permuted = x_original.permute(2, 0, 1) # permutes axis
x_permuted.shape

torch.Size([3, 224, 224])

### Indexing

In [56]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [57]:
x[0, 0]

tensor([1, 2, 3])

In [58]:
x[0][1][2]

tensor(6)

In [59]:
x[0, :, 1]

tensor([2, 5, 8])

In [60]:
x[:, 1, 1]

tensor([5])

In [61]:
x[0, 0, :]

tensor([1, 2, 3])

In [62]:
x[0, 2, 2]


tensor(9)

In [63]:
x[0, :, 2]

tensor([3, 6, 9])

### Tensors and NumPy

* `torch.from_numpy(nparray)` - takes data from NumPy array and converts to a tensor
* `torch.tensor.numpy()` - takes pytorch tensor to numpy array

In [64]:
import torch
import numpy as np

array = np.arange(1., 8.)
tensor = torch.from_numpy(array)
array, tensor
# default numpy dtype is float64, pytorch reflects this, unless specified otherwise

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [65]:
array.dtype

dtype('float64')

In [66]:
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [67]:
# from tensor to numpy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [68]:
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducability

to reduce randomness in pytorch and neural networks -> `Random Seed`

In [69]:
import torch

randomA = torch.rand(3, 4)
randomB = torch.rand(3, 4)

print(randomA)
print(randomB)
print(randomA == randomB)

tensor([[0.9094, 0.7585, 0.0885, 0.8717],
        [0.9611, 0.5063, 0.8067, 0.5961],
        [0.3416, 0.8718, 0.2919, 0.9445]])
tensor([[0.0710, 0.7079, 0.0868, 0.4264],
        [0.2653, 0.6069, 0.6370, 0.3084],
        [0.1568, 0.8531, 0.9694, 0.6087]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [70]:
# make random but reproducable tensors
# random seed (.manual_Seed()) adds "Flavour" or randomness

RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
randomC = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
randomD = torch.rand(3, 4)
print(randomC)
print(randomD)
print(randomC == randomD)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Running tensors and pytorch objects on GPU (making faster computations)

* google colab
* purchase GPU
* cloud computing - GCP, AWS, Azure

In [71]:
import torch
torch.cuda.is_available()

True

In [72]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [73]:
# counts number of devices
torch.cuda.device_count()

1

## Putting tensors (and models) on the GPU

In [74]:
# Create a tensor
tensor = torch.tensor([1, 2, 3])

# tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [75]:
# Move tensor to GPU if available
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [78]:
# Move tensors back to CPU
# tensor_on_gpu.numpy() causes device ERROR, must set tp CPU

tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])