<a href="https://colab.research.google.com/github/DerekHickey6/derekhickey6.github.io/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import torch
import pandas as pd
import numpy as pd
import matplotlib.pyplot as plt

print(torch.__version__)

2.8.0+cu126


In [12]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [13]:
vector.shape

torch.Size([2])

In [14]:
matrix = torch.tensor([[7,6],
                       [8,9]])
matrix

tensor([[7, 6],
        [8, 9]])

In [15]:
matrix.ndim

2

In [16]:
matrix[1]

tensor([8, 9])

In [17]:
matrix.shape

torch.Size([2, 2])

In [18]:
matrix = torch.tensor([[7,6],
                       [8,9]])
matrix.shape

torch.Size([2, 2])

In [19]:
matrix.shape

torch.Size([2, 2])

In [21]:
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [22]:
TENSOR.ndim

3

In [23]:
TENSOR.shape

torch.Size([1, 3, 3])

In [26]:
TENSOR[0]

tensor([1, 2, 3])