<a href="https://colab.research.google.com/github/DerekHickey6/derekhickey6.github.io/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
import torch
import pandas as pd
import numpy as pd
import matplotlib.pyplot as plt

print(torch.__version__)

2.8.0+cu126


### Scalar/Vector/MATRIX/TENSOR

In [28]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [29]:
vector.shape

torch.Size([2])

In [30]:
MATRIX = torch.tensor([[7,6],
                       [8,9]])
MATRIX

tensor([[7, 6],
        [8, 9]])

In [31]:
MATRIX.ndim

2

In [32]:
MATRIX[1]

tensor([8, 9])

In [33]:
MATRIX.shape

torch.Size([2, 2])

In [34]:
MATRIX = torch.tensor([[7,6],
                       [8,9]])
MATRIX.shape

torch.Size([2, 2])

In [35]:
MATRIX.shape

torch.Size([2, 2])

In [36]:
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [37]:
TENSOR.ndim

3

In [38]:
TENSOR.shape

torch.Size([1, 3, 3])

In [39]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random Tensors

In [46]:
# create random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.0952, 0.2710, 0.7737, 0.8683],
        [0.3816, 0.6701, 0.3699, 0.9043],
        [0.4661, 0.6427, 0.1541, 0.7835]])

In [47]:
random_tensor.ndim

2

In [50]:
# create a random tensor with similar shape as an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # color channels (R, G, B), height, width,
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Tensors of ones / zeros & Range

In [56]:
# Create a tensor of all zeros
zero = torch.zeros(3,4)
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [57]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [58]:
ones.dtype

torch.float32

In [65]:
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
# creating tensor-like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Data Types

In [69]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                                dtype=None,           # Data type of tensor
                                device=None,          # Device that tensor on
                                requires_grad=False)  # Tracks the gradients of a tensor while going through numerical calculations
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [70]:
float_32_tensor.dtype

torch.float16

In [71]:
float_16_tensor = float_32_tensor.type(torch.half)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [73]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

### Getting information from tensors

1. get datatype from tensor `tensor.type`
2. get shape from tensor `tensor.shape`
3. get device from a tensor `tensor.device`


In [74]:
# Create a Tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.0962, 0.6809, 0.4718, 0.5879],
        [0.0208, 0.2050, 0.6323, 0.0202],
        [0.0658, 0.3781, 0.4723, 0.0591]])

In [75]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.0962, 0.6809, 0.4718, 0.5879],
        [0.0208, 0.2050, 0.6323, 0.0202],
        [0.0658, 0.3781, 0.4723, 0.0591]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


### Manipulating Tensor (operations)


In [96]:
# Create a tensor and add 100
tensor = torch.tensor([1,2,3])
tensor + 100

tensor([101, 102, 103])

In [77]:
# Tensor multiplied by 10
tensor * 10

tensor([10, 20, 30])

In [78]:
# subtract 10
tensor - 10

tensor([-9, -8, -7])

In [97]:
# Using PyTorch functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

### Matrix Multiplication

In [98]:
# Element Wise Multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")
tensor


tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


tensor([1, 2, 3])

In [105]:
# Matrix Multiplication
%%time
torch.matmul(torch.rand(50), torch.rand(50))

CPU times: user 571 µs, sys: 18 µs, total: 589 µs
Wall time: 894 µs


tensor(11.3042)

In [106]:
# Matrix multiplication by hand
%%time
value = 0
for i in range(len(tensor)):
  value += torch.rand(50)[i] * torch.rand(50)[i]
print(value)

tensor(0.3349)
CPU times: user 2.57 ms, sys: 0 ns, total: 2.57 ms
Wall time: 2.93 ms


In [100]:
# Other notation for matmul
tensor @ tensor

tensor(14)

In [110]:
# Shapes for matrix multiplications
tensor_A = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]])
tensor_B = torch.tensor([[7, 10],
                        [8, 11],
                        [9, 12]])
torch.mm(tensor_A, tensor_B.T)  # .T is transpose

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])